CREATE TABLE  (
transactionId INTEGER NOT NULL AUTO_INCREMENT UNIQUE,

id INTEGER NOT NULL,

accName VARCHAR(25) NOT NULL,

accNum int(10) NOT NULL,

recBank VARCHAR(25) NOT NULL,

recAccName VARCHAR(25) NOT NULL,

recAccNum int(10) NOT NULL,

transactionDate TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP
)

ENGINE = MyISAM DEFAULT CHARACTER SET latin1     

COLLATE latin1_general_cs
